query stopPlaceQuayDepartures(
  $id: String!
  $numberOfDepartures: Int
  $startTime: DateTime
) {
  stopPlace(id: $id) {
    id
    name
    latitude
    longitude
    transportMode
    transportSubmode
    description
    quays(filterByInUse: true) {
      id
      name
      publicCode
      description
      estimatedCalls(
        numberOfDepartures: $numberOfDepartures
        startTime: $startTime
        includeCancelledTrips: true
      ) {
        date
        expectedDepartureTime
        aimedDepartureTime
        realtime
        cancellation
        quay {
          id
        }
        destinationDisplay {
          frontText
        }
        serviceJourney {
          id
          line {
            id
            description
            publicCode
            transportMode
            transportSubmode
          }
        }
      }
    }
  }
}
