query nearestStopPlaces(
  $count: Int = 10
  $distance: Float!
  $longitude: Float!
  $latitude: Float!
  $after: String
) {
  nearest(
    latitude: $latitude
    longitude: $longitude
    maximumDistance: $distance
    first: $count
    after: $after
    filterByInUse: true
    filterByPlaceTypes: stopPlace
    multiModalMode: parent
  ) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        distance
        place {
          ...stopPlace
        }
      }
    }
  }
}

fragment stopPlace on StopPlace {
  name
  description
  quays(filterByInUse: true) {
    id
    description
    name
    publicCode
    stopPlace {
      id
      transportMode
    }
    situations {
      ...situation
    }
  }
  transportMode
  description
  id
  latitude
  longitude
}
