query getStopPlace($id: String!) {
  stopPlace(id: $id) {
    name
    id
    description

    latitude
    longitude

    quays {
      ...stopPlaceQuay
    }
  }
}

fragment stopPlaceQuay on Quay {
  id
}
