query ViaTrips(
  $from: Location!
  $to: Location!
  $when: DateTime
  $via: [ViaLocationInput!]!
  $segments: [ViaSegmentInput!]
) {
  viaTrip(
    from: $from
    to: $to
    searchWindow: "PT9H"
    dateTime: $when
    via: $via
    segments: $segments
  ) {
    ...viaTrip
  }
}

fragment viaTrip on ViaTrip {
  tripPatternsPerSegment {
    ...tripPatternsPerSegment
  }
  tripPatternCombinations {
    from
    to
  }
}

fragment tripPatternsPerSegment on ViaTripPatternSegment {
  tripPatterns {
    expectedStartTime
    expectedEndTime
    streetDistance
    legs {
      mode
      intermediateEstimatedCalls {
        aimedDepartureTime
      }
      serviceJourneyEstimatedCalls {
        aimedDepartureTime
        expectedDepartureTime
        actualDepartureTime
        cancellation
        quay {
          name
          description
        }
        realtime
      }
      distance
      duration
      aimedStartTime
      expectedEndTime
      expectedStartTime
      realtime
      aimedEndTime
      pointsOnLink {
        points
      }
      line {
        publicCode
        flexibleLineType
        notices {
          ...notice
        }
        flexibleLineType
      }
      fromEstimatedCall {
        cancellation
        notices {
          ...notice
        }
      }
      toEstimatedCall {
        cancellation
        notices {
          ...notice
        }
      }
      situations {
        ...situation
      }
      fromPlace {
        name
        longitude
        latitude
        quay {
          publicCode
          name
          description
          id
          situations {
            ...situation
          }
        }
      }
      toPlace {
        name
        longitude
        latitude
        quay {
          publicCode
          name
          description
          id
          situations {
            ...situation
          }
        }
      }
      serviceJourney {
        id
        notices {
          ...notice
        }
        journeyPattern {
          notices {
            ...notice
          }
        }
      }
      transportSubmode
    }
  }
}
