query TripsWithDetails(
  $from: Location!
  $to: Location!
  $arriveBy: Boolean!
  $when: DateTime
  $cursor: String
  $transferPenalty: Int
  $transferSlack: Int
  $waitReluctance: Float
  $walkReluctance: Float
  $walkSpeed: Float
  $modes: Modes
  $numTripPatterns: Int
  $lineFilter: [ID]
) {
  trip(
    from: $from
    to: $to
    dateTime: $when
    arriveBy: $arriveBy
    pageCursor: $cursor
    transferPenalty: $transferPenalty
    transferSlack: $transferSlack
    waitReluctance: $waitReluctance
    walkReluctance: $walkReluctance
    walkSpeed: $walkSpeed
    modes: $modes
    numTripPatterns: $numTripPatterns
    searchWindow: 60 # 1 hour
    includeRealtimeCancellations: true
    includePlannedCancellations: true
    whiteListed: { lines: $lineFilter }
  ) {
    tripPatterns {
      expectedStartTime
      expectedEndTime
      streetDistance
      legs {
        mode
        transportSubmode
        aimedStartTime
        aimedEndTime
        expectedStartTime
        expectedEndTime
        realtime
        duration
        pointsOnLink {
          points
          length
        }
        line {
          name
          publicCode
          notices {
            ...notice
          }
        }
        fromPlace {
          name
          latitude
          longitude
          quay {
            id
            name
            publicCode
          }
        }
        toPlace {
          name
          latitude
          longitude
          quay {
            name
            publicCode
          }
        }
        serviceJourney {
          id
          notices {
            ...notice
          }
          journeyPattern {
            notices {
              ...notice
            }
          }
        }
        fromEstimatedCall {
          notices {
            ...notice
          }
          destinationDisplay {
            frontText
          }
          cancellation
        }
        interchangeTo {
          guaranteed
          toServiceJourney {
            id
          }
        }
        intermediateEstimatedCalls {
          aimedDepartureTime
        }
        situations {
          ...situation
        }
      }
    }
  }
}
