query Trips(
  $from: Location!
  $to: Location!
  $arriveBy: Boolean!
  $when: DateTime
  $cursor: String
  $transferPenalty: Int
  $transferSlack: Int
  $waitReluctance: Float
  $walkReluctance: Float
  $walkSpeed: Float
  $modes: Modes
  $numTripPatterns: Int
  $lineFilter: [ID]
) {
  trip(
    from: $from
    to: $to
    dateTime: $when
    arriveBy: $arriveBy
    pageCursor: $cursor
    transferPenalty: $transferPenalty
    transferSlack: $transferSlack
    waitReluctance: $waitReluctance
    walkReluctance: $walkReluctance
    walkSpeed: $walkSpeed
    modes: $modes
    numTripPatterns: $numTripPatterns
    searchWindow: 540 # 9 hours
    includeRealtimeCancellations: true
    includePlannedCancellations: true
    whiteListed: { lines: $lineFilter }
  ) {
    ...trip
  }
}

query TripsNonTransit(
  $from: Location!
  $to: Location!
  $arriveBy: Boolean!
  $when: DateTime
  $walkSpeed: Float
  $includeFoot: Boolean!
  $includeBicycle: Boolean!
  $includeBikeRental: Boolean!
) {
  footTrip: trip(
    from: $from
    to: $to
    dateTime: $when
    arriveBy: $arriveBy
    numTripPatterns: 1
    walkSpeed: $walkSpeed
    modes: { directMode: foot, transportModes: [] }
  ) @include(if: $includeFoot) {
    tripPatterns {
      ...nonTransitTrip
    }
  }
  bikeRentalTrip: trip(
    from: $from
    to: $to
    dateTime: $when
    arriveBy: $arriveBy
    walkSpeed: $walkSpeed
    numTripPatterns: 1
    modes: { directMode: bike_rental, transportModes: [] }
  ) @include(if: $includeBikeRental) {
    tripPatterns {
      ...nonTransitTrip
    }
  }
  bicycleTrip: trip(
    from: $from
    to: $to
    dateTime: $when
    arriveBy: $arriveBy
    numTripPatterns: 1
    walkSpeed: $walkSpeed
    modes: { directMode: bicycle, transportModes: [] }
  ) @include(if: $includeBicycle) {
    tripPatterns {
      ...nonTransitTrip
    }
  }
}

fragment trip on Trip {
  nextPageCursor
  previousPageCursor
  metadata {
    searchWindowUsed
  }
  tripPatterns {
    ...tripPattern
  }
}

fragment tripPattern on TripPattern {
  expectedStartTime
  expectedEndTime
  streetDistance
  legs {
    mode
    distance
    duration
    aimedStartTime
    expectedEndTime
    expectedStartTime
    realtime
    line {
      publicCode
      flexibleLineType
      notices {
        ...notice
      }
      flexibleLineType
    }
    fromEstimatedCall {
      cancellation
      notices {
        ...notice
      }
    }
    situations {
      ...situation
    }
    fromPlace {
      name
      quay {
        publicCode
        name
        description
        id
        situations {
          ...situation
        }
      }
    }
    serviceJourney {
      id
      notices {
        ...notice
      }
      journeyPattern {
        notices {
          ...notice
        }
      }
    }
    transportSubmode
    interchangeTo {
      staySeated
    }
  }
}

fragment notice on Notice {
  id
  text
}

fragment situation on PtSituationElement {
  id
  situationNumber
  summary {
    ...multilingualString
  }
  description {
    ...multilingualString
  }
  reportType
  advice {
    ...multilingualString
  }
  infoLinks {
    ...infoLink
  }
  validityPeriod {
    ...validityPeriod
  }
}

fragment tariffZone on TariffZone {
  id
  name
}

fragment bookingArrangement on BookingArrangement {
  bookingMethods
  latestBookingTime
  bookingNote
  bookWhen
  latestBookingTime
  minimumBookingPeriod
  bookingContact {
    contactPerson
    email
    url
    phone
    furtherDetails
  }
}

fragment multilingualString on MultilingualString {
  language
  value
}

fragment infoLink on infoLink {
  uri
  label
}

fragment validityPeriod on ValidityPeriod {
  startTime
  endTime
}

fragment nonTransitTrip on TripPattern {
  duration
  legs {
    mode
    rentedBike
    aimedStartTime
  }
}
