name: Docker Build, Push & Deploy

on:
  release:
    types: [published]
  push:
    branches: ['main']

jobs:
  build:
    uses: atb-as/workflows/.github/workflows/cluster-docker-build-tag-push.yaml@v2
    with:
      image: europe-west1-docker.pkg.dev/amp-artifacts/amp/planner-web
      build_args: |
        ATB_NEXT_PUBLIC_MAPBOX_DEFAULT_LAT=63.43457
        ATB_NEXT_PUBLIC_MAPBOX_DEFAULT_LNG=10.39844
        ATB_NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ github.event_name == 'release' && 'atb-mobility-platform' || 'atb-mobility-platform-staging'}}
        ATB_NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY=${{ github.event_name == 'release' && 'AIzaSyBiw58LOLaBGiNYI1_bj5J8jC5E56WxmB8' || 'AIzaSyDoat8ob5tewAXaPEhqbZKzx8e7LC5nuzQ' }}
        ATB_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ github.event_name == 'release' && 'atb-mobility-platform.firebaseapp.com' || 'atb-mobility-platform-staging.firebaseapp.com' }}
        ATB_NEXT_PUBLIC_FIREBASE_APP_ID=${{ github.event_name == 'release' && '1:827196677776:web:c4b1d8924bb5778bf50215' || '1:939812594010:web:0308b2a9cdc80b0d069363' }}
        ATB_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ github.event_name == 'release' && '' || '' }}
        NFK_NEXT_PUBLIC_MAPBOX_DEFAULT_LAT=67.280357
        NFK_NEXT_PUBLIC_MAPBOX_DEFAULT_LNG=14.404916
        NFK_NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ github.event_name == 'release' && 'nfk-prod' || 'nfk-staging'}}
        NFK_NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY=${{ github.event_name == 'release' && 'AIzaSyDGwZLvjhRJmxiU9BOkbYn9P78QTJsAaBQ' || 'AIzaSyDU18r0GPKIGcVxA3Zj_zgkrtqaUfcOHGM' }}
        NFK_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ github.event_name == 'release' && 'nfk-prod.firebaseapp.com' || 'nfk-staging.firebaseapp.com' }}
        NFK_NEXT_PUBLIC_FIREBASE_APP_ID=${{ github.event_name == 'release' && '1:638315587956:web:51e95a11a03f27dc9ca421' || '1:793301954236:web:908723b8ded2824cadeab9' }}
        NFK_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ github.event_name == 'release' && '' || '' }}
        FRAM_NEXT_PUBLIC_MAPBOX_DEFAULT_LAT=62.4705
        FRAM_NEXT_PUBLIC_MAPBOX_DEFAULT_LNG=6.1533
        FRAM_NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ github.event_name == 'release' && 'fram-prod-a7850' || 'fram-staging'}}
        FRAM_NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY=${{ github.event_name == 'release' && 'AIzaSyBw6YwFJV__iw6Qp7bLdcwcUKtr2f02H2M' || 'AIzaSyBTsBaCnXcCFPQUaXTPLSMGfydaTpaLDrs' }}
        FRAM_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ github.event_name == 'release' && 'fram-prod-a7850.firebaseapp.com' || 'fram-staging.firebaseapp.com' }}
        FRAM_NEXT_PUBLIC_FIREBASE_APP_ID=${{ github.event_name == 'release' && '1:717595301444:web:1e16129330d562f1b3ce11' || '1:312905478211:web:41c6f9db83ae5ef0efa4f6' }}
        FRAM_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ github.event_name == 'release' && 'G-KS45JBFWF4' || '' }}
        FRAM_NEXT_PUBLIC_CONTACT_API_URL=${{ github.event_name == 'release' && 'https://pureservice-connect-9ccec9fd5b4f.herokuapp.com' || 'https://pureservice-connect-staging-744284a2bb1b.herokuapp.com'}}
        TROMS_NEXT_PUBLIC_MAPBOX_DEFAULT_LAT=69.665229
        TROMS_NEXT_PUBLIC_MAPBOX_DEFAULT_LNG=18.9070347
        TROMS_NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ github.event_name == 'release' && 'troms-prod' || 'troms-staging'}}
        TROMS_NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY=${{ github.event_name == 'release' && 'AIzaSyAzGgJ8ne8N4CIfASHao3YpOsUvZfOAdiE' || 'AIzaSyCtJMximw0SL9N8YNH21TWDO0s_mv_9crE' }}
        TROMS_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ github.event_name == 'release' && 'troms-prod.firebaseapp.com' || 'troms-staging.firebaseapp.com' }}
        TROMS_NEXT_PUBLIC_FIREBASE_APP_ID=${{ github.event_name == 'release' && '1:667141878008:web:b1a8f3e21716e96e954b0d' || '1:973624729382:web:a84d8a489613a14be12be7' }}
        TROMS_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ github.event_name == 'release' && 'G-ZDRTXVTCQD' || '' }}
        VKT_NEXT_PUBLIC_MAPBOX_DEFAULT_LAT=59.2676
        VKT_NEXT_PUBLIC_MAPBOX_DEFAULT_LNG=10.4076
        VKT_NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ github.event_name == 'release' && 'vkt-prod' || 'vkt-staging'}}
        VKT_NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY=${{ github.event_name == 'release' && 'AIzaSyABOU4H1V7BdzKgcXLIhfadfHzzR2f4Wek' || 'AIzaSyDYGwv-yLw74g8AGScBYNMB1lmlHeysE1c' }}
        VKT_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ github.event_name == 'release' && 'vkt-prod.firebaseapp.com' || 'vkt-staging.firebaseapp.com' }}
        VKT_NEXT_PUBLIC_FIREBASE_APP_ID=${{ github.event_name == 'release' && '1:49488006744:web:841bff9c5027e1ce6d442d' || '1:404908406633:web:1aea6ddfaab3f65727eff8' }}
        VKT_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ github.event_name == 'release' && 'G-P644YTVLQS' || 'G-YM2VV1NXH0' }}
        FARTE_NEXT_PUBLIC_MAPBOX_DEFAULT_LAT=59.2089
        FARTE_NEXT_PUBLIC_MAPBOX_DEFAULT_LNG=9.6058
        FARTE_NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ github.event_name == 'release' && 'farte-prod' || 'farte-staging'}}
        FARTE_NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY=${{ github.event_name == 'release' && 'AIzaSyDrDpsYNZZlU4xCK3vkPoyM0QDZ-aItGfQ' || 'AIzaSyCk_rY7MbfnSt38-vIjtk7i8jyXntcFGp8' }}
        FARTE_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ github.event_name == 'release' && 'farte-prod.firebaseapp.com' || 'farte-staging.firebaseapp.com' }}
        FARTE_NEXT_PUBLIC_FIREBASE_APP_ID=${{ github.event_name == 'release' && '1:944925576120:web:fba23d38e7de3d61a59d4d' || '1:779243067725:web:0675c351ed484c537bbf04' }}
        FARTE_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ github.event_name == 'release' && 'G-GSL7WE0NQL' || 'G-5V6FPCN5JF' }}
        NEXT_PUBLIC_ENVIRONMENT=${{ github.event_name == 'release' && 'prod' || 'staging' }}
    secrets:
      github_pat: ${{ secrets.GH_PAT }}
      build_secrets: |
        ATB_NEXT_PUBLIC_MAPBOX_API_TOKEN=${{ secrets.ATB_NEXT_PUBLIC_MAPBOX_API_TOKEN }}
        ATB_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL=${{ secrets.ATB_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL }}
        NFK_NEXT_PUBLIC_MAPBOX_API_TOKEN=${{ secrets.NFK_NEXT_PUBLIC_MAPBOX_API_TOKEN }}
        NFK_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL=${{ secrets.NFK_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL }}
        FRAM_NEXT_PUBLIC_MAPBOX_API_TOKEN=${{ github.event_name == 'release' && secrets.FRAM_NEXT_PUBLIC_MAPBOX_API_TOKEN || secrets.FRAM_NEXT_PUBLIC_MAPBOX_API_TOKEN_STAGING }}
        FRAM_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL=${{ secrets.FRAM_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL }}
        TROMS_NEXT_PUBLIC_MAPBOX_API_TOKEN=${{ secrets.TROMS_NEXT_PUBLIC_MAPBOX_API_TOKEN }}
        TROMS_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL=${{ secrets.TROMS_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL }}
        VKT_NEXT_PUBLIC_MAPBOX_API_TOKEN=${{ secrets.VKT_NEXT_PUBLIC_MAPBOX_API_TOKEN }}
        VKT_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL=${{ secrets.VKT_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL }}
        FARTE_NEXT_PUBLIC_MAPBOX_API_TOKEN=${{ secrets.FARTE_NEXT_PUBLIC_MAPBOX_API_TOKEN }}
        FARTE_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL=${{ secrets.FARTE_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL }}
