name: Docker Build, Push & Deploy

on:
  release:
    types: [published]
  push:
    branches: ['morten/fix-gha-workflow']

jobs:
  build:
    uses: atb-as/workflows/.github/workflows/cluster-docker-build-tag-push.yaml@v2
    with:
      image: gcr.io/atb-mobility-platform/planner-web
      build_args: |
        FRAM_NEXT_PUBLIC_MAPBOX_DEFAULT_LAT=62.734541
        FRAM_NEXT_PUBLIC_MAPBOX_DEFAULT_LNG=7.151046
        ATB_NEXT_PUBLIC_MAPBOX_DEFAULT_LAT=63.43457
        ATB_NEXT_PUBLIC_MAPBOX_DEFAULT_LNG=10.39844
        NFK_NEXT_PUBLIC_MAPBOX_DEFAULT_LAT=67.280357
        NFK_NEXT_PUBLIC_MAPBOX_DEFAULT_LNG=14.404916
    secrets:
      github_pat: ${{ secrets.GH_PAT }}
      ATB_NEXT_PUBLIC_MAPBOX_API_TOKEN:
        ${{ secrets.ATB_NEXT_PUBLIC_MAPBOX_API_TOKEN }}
      ATB_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL:
        ${{ secrets.ATB_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL }}
      NFK_NEXT_PUBLIC_MAPBOX_API_TOKEN:
        ${{ secrets.NFK_NEXT_PUBLIC_MAPBOX_API_TOKEN }}
      NFK_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL:
        ${{ secrets.NFK_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL }}
      FRAM_NEXT_PUBLIC_MAPBOX_API_TOKEN:
        ${{ secrets.FRAM_NEXT_PUBLIC_MAPBOX_API_TOKEN }}
      FRAM_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL:
        ${{ secrets.FRAM_NEXT_PUBLIC_MAPBOX_STOP_PLACES_STYLE_URL }}
