name: Playwright Tests
on:
  deployment_status:

jobs:
  test:
    if:
      github.event_name == 'deployment_status' &&
      github.event.deployment_status.state == 'success' &&
      endsWith(github.event.deployment.environment, 'Preview')

    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Yarn Dependencies
        run: yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn playwright test
        env:
          NEXT_PUBLIC_PLANNER_ORG_ID: atb
          E2E_URL: ${{ github.event.deployment_status.target_url }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
